---
- name: installing apache
  hosts: ubuntu
  become: true
  tasks:
  - name: install apache
    apt: name=apache2 update_cache=yes state=latest
  - name: copy files to document root
    copy: src=cloud.png dest=/var/www/html/cloud.png
  - name: apache2 listen on port 80
    lineinfile: dest=/etc/apache2/ports.conf regexp="^Listen 8081" line="Listen 80" state=present
    notify:
    - restart apache2

  - name: apache2 virtualhost on port 80
    lineinfile: dest=/etc/apache2/sites-available/000-default.conf regexp="^<VirtualHost \*:8081>" line="<VirtualHost *:80>" state=present
    notify:
        - restart apache2
  handlers:
  - name: restart apache2
    service: name=apache2 state=restarted

